services:
  vnrg:
    image: postgres:15-alpine
    container_name: vnrg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vnrg
    ports:
      - '2333:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
