'use client'

export { ProductPageSection } from './ProductPageSection'
export { ProductHeroSection } from './ProductHeroSection'
export { ProductOverviewSection } from './ProductOverviewSection'
export { ProductTabsSection } from './ProductTabsSection'
export { ProductComparisonSection } from './ProductComparisonSection'
export { ProductCertificatesSection } from './ProductCertificatesSection'
export { ProductReviewsSection } from './ProductReviewsSection'
export { ProductCardsSection } from './ProductCardsSection'
