import fs from 'node:fs/promises'
import path from 'node:path'
import { Client } from 'pg'
import ts from 'typescript'

const root = process.cwd()
const sourceRoot = path.join(root, 'src', 'app', '(frontend)')
const outputFile = path.join(sourceRoot, 'lib', 'generatedEnglishTranslations.ts')
const databaseURL =
  process.env.TRANSLATION_DATABASE_URL || 'postgresql://postgres:password@127.0.0.1:2333/vnrg'

const cyrillic = /[А-Яа-яІіЇїЄєҐґ]/
const cache = new Map()

async function translate(text) {
  const normalized = text.trim()
  if (!normalized || !cyrillic.test(normalized)) return text
  if (cache.has(normalized)) return cache.get(normalized)

  const url = new URL('https://translate.googleapis.com/translate_a/single')
  url.searchParams.set('client', 'gtx')
  url.searchParams.set('sl', 'uk')
  url.searchParams.set('tl', 'en')
  url.searchParams.set('dt', 't')
  url.searchParams.set('q', normalized)

  const response = await fetch(url)
  if (!response.ok) throw new Error(`Translation failed (${response.status}): ${normalized}`)
  const data = await response.json()
  const translated = data[0].map((part) => part[0]).join('')
  cache.set(normalized, translated)
  await new Promise((resolve) => setTimeout(resolve, 40))
  return translated
}

async function walk(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(fullPath)))
    else if (/\.(ts|tsx)$/.test(entry.name) && !entry.name.includes('generatedEnglishTranslations')) files.push(fullPath)
  }
  return files
}

function extractStrings(source) {
  const values = new Set()
  const file = ts.createSourceFile('source.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX)
  const visit = (node) => {
    if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node) || ts.isJsxText(node)) {
      const clean = node.text.replace(/\s+/g, ' ').trim()
      if (clean && clean.length < 500 && cyrillic.test(clean)) values.add(clean)
    }
    ts.forEachChild(node, visit)
  }
  visit(file)
  return values
}

async function generateStaticDictionary() {
  const strings = new Set()
  for (const file of await walk(sourceRoot)) {
    const source = await fs.readFile(file, 'utf8')
    for (const value of extractStrings(source)) strings.add(value)
  }

  const entries = []
  for (const value of [...strings].sort((a, b) => a.localeCompare(b, 'uk'))) {
    entries.push([value, await translate(value)])
  }

  const content = `// Generated by scripts/translate-to-en.mjs\nexport const generatedEnglishTranslations: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`
  await fs.writeFile(outputFile, content, 'utf8')
  console.log(`Generated ${entries.length} static translations.`)
}

async function translateDatabase() {
  const client = new Client({ connectionString: databaseURL })
  await client.connect()

  const tables = await client.query(`
    select table_name
    from information_schema.tables
    where table_schema = 'public' and table_name like '%\\_locales' escape '\\'
    order by table_name
  `)

  for (const { table_name: table } of tables.rows) {
    const columnsResult = await client.query(
      `select column_name, data_type from information_schema.columns
       where table_schema='public' and table_name=$1
         and column_name not in ('id','_locale','_parent_id')
       order by ordinal_position`,
      [table],
    )
    const columns = columnsResult.rows
    if (!columns.length) continue

    const ukRows = await client.query(`select * from "${table}" where "_locale"='uk'`)
    for (const row of ukRows.rows) {
      const values = {}
      for (const column of columns) {
        values[column.column_name] = await translateValue(row[column.column_name])
      }

      const names = columns.map((column) => `"${column.column_name}"`)
      const params = columns.map((column) => values[column.column_name])
      const updates = columns.map((column, index) => `"${column.column_name}"=$${index + 2}`)
      await client.query(
        `insert into "${table}" ("_parent_id","_locale",${names.join(',')})
         values ($1,'en',${columns.map((_, index) => `$${index + 2}`).join(',')})
         on conflict ("_locale","_parent_id") do update set ${updates.join(',')}`,
        [row._parent_id, ...params],
      )
    }
    console.log(`Translated ${table}: ${ukRows.rowCount} rows.`)
  }

  await client.end()
}

async function translateValue(value) {
  if (typeof value === 'string') return cyrillic.test(value) ? translate(value) : value
  if (Array.isArray(value)) return Promise.all(value.map(translateValue))
  if (value && typeof value === 'object') {
    const result = {}
    for (const [key, nestedValue] of Object.entries(value)) result[key] = await translateValue(nestedValue)
    return result
  }
  return value
}

await generateStaticDictionary()
await translateDatabase()
