/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    reviews: Review;
    products: Product;
    category: Category;
    articles: Article;
    orders: Order;
    'legal-pages': LegalPage;
    locations: Location;
    'training-categories': TrainingCategory;
    'training-videos': TrainingVideo;
    applications: Application;
    'dealer-applications': DealerApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'training-categories': TrainingCategoriesSelect<false> | TrainingCategoriesSelect<true>;
    'training-videos': TrainingVideosSelect<false> | TrainingVideosSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'dealer-applications': DealerApplicationsSelect<false> | DealerApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    training: Training;
    contacts: Contact;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    training: TrainingSelect<false> | TrainingSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  role: 'admin' | 'user' | 'dealer';
  /**
   * Відсоток знижки на товари для дилерського акаунта.
   */
  dealerDiscountPercent?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  avatar: number | Media;
  text?: string | null;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  price: number;
  rating?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category?: (number | Category)[] | null;
  maniples?: number | null;
  powerWatts?: number | null;
  oldprice?: number | null;
  /**
   * Наприклад: 18 маніпул · 800 Вт.
   */
  details?: string | null;
  shortDescription?: string | null;
  gallery?: (number | Media)[] | null;
  listFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  compareFeatures?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  characteristics?: {
    items?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  equipment?: {
    items?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  advantages?: {
    items?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  video?: {
    items?: (number | Media)[] | null;
    description?: string | null;
  };
  reviews?: (number | Review)[] | null;
  moreProducts?: (number | Product)[] | null;
  recommendedTogether?: (number | Product)[] | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  beforeafter?:
    | {
        before?: (number | null) | Media;
        after?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: number;
  image: number | Media;
  title?: string | null;
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  publishedAt: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  cardPoster: number | Media;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer?: (number | null) | User;
  firstName: string;
  lastName: string;
  phone: string;
  customerEmail: string;
  orderStatus: 'new' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymentStatus: 'awaiting_payment' | 'processing' | 'paid' | 'failed' | 'refunded';
  paymentMethod: 'card-online' | 'monobank-parts' | 'invoice' | 'cash-on-delivery';
  total: number;
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  delivery?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  comment?: string | null;
  monobank?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Fallback. Якщо заповнений Lexical-контент, на фронті використовується він.
   */
  contentMarkdown?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  country: string;
  city: string;
  address: string;
  image?: (number | null) | Media;
  latitude: number;
  longitude: number;
  phone?: string | null;
  instagram?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-categories".
 */
export interface TrainingCategory {
  id: number;
  title: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-videos".
 */
export interface TrainingVideo {
  id: number;
  title: string;
  description: string;
  category: number | TrainingCategory;
  poster: number | Media;
  video: number | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  source: 'contacts' | 'hero-popup';
  name: string;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  status: 'new' | 'processing' | 'completed' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-applications".
 */
export interface DealerApplication {
  id: number;
  account: number | User;
  companyName: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  city: string;
  message?: string | null;
  status: 'new' | 'processing' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'category';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'training-categories';
        value: number | TrainingCategory;
      } | null)
    | ({
        relationTo: 'training-videos';
        value: number | TrainingVideo;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'dealer-applications';
        value: number | DealerApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  role?: T;
  dealerDiscountPercent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  avatar?: T;
  text?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  rating?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  maniples?: T;
  powerWatts?: T;
  oldprice?: T;
  details?: T;
  shortDescription?: T;
  gallery?: T;
  listFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  compareFeatures?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  description?:
    | T
    | {
        content?: T;
      };
  characteristics?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  equipment?:
    | T
    | {
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  advantages?:
    | T
    | {
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  video?:
    | T
    | {
        items?: T;
        description?: T;
      };
  reviews?: T;
  moreProducts?: T;
  recommendedTogether?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  beforeafter?:
    | T
    | {
        before?: T;
        after?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  image?: T;
  title?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  cardPoster?: T;
  heroImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  customerEmail?: T;
  orderStatus?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  total?: T;
  items?: T;
  delivery?: T;
  comment?: T;
  monobank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  content?: T;
  contentMarkdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  city?: T;
  address?: T;
  image?: T;
  latitude?: T;
  longitude?: T;
  phone?: T;
  instagram?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-categories_select".
 */
export interface TrainingCategoriesSelect<T extends boolean = true> {
  title?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-videos_select".
 */
export interface TrainingVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  poster?: T;
  video?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  source?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-applications_select".
 */
export interface DealerApplicationsSelect<T extends boolean = true> {
  account?: T;
  companyName?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  city?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Контент головної сторінки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    title: string;
    description: string;
    image: number | Media;
  };
  howItWork: {
    title: string;
    subtitle: string;
    cards?:
      | {
          icon: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  beforeAfter?:
    | {
        before: number | Media;
        after: number | Media;
        id?: string | null;
      }[]
    | null;
  modelComparison: {
    title: string;
    subtitle: string;
    products?: (number | Product)[] | null;
  };
  certificatesSection: {
    title: string;
    subtitle: string;
    certificates?: (number | Media)[] | null;
  };
  trainingSection: {
    title: string;
    subtitle: string;
    video: {
      poster: number | Media;
      file: number | Media;
    };
    cards?:
      | {
          icon: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  reviewsSection: {
    title: string;
    subtitle: string;
    reviews?: (number | Review)[] | null;
  };
  faqSection: {
    title: string;
    subtitle: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент сторінки навчання.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training".
 */
export interface Training {
  id: number;
  title: string;
  description: string;
  formats: {
    title: string;
    subtitle: string;
    cards?:
      | {
          icon: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  videoInstructions: {
    title: string;
    subtitle: string;
  };
  faq: {
    title: string;
    subtitle: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент сторінки контактів.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  title: string;
  description: string;
  phone: string;
  email: string;
  address: string;
  form: {
    title: string;
    description: string;
    socialNetworks?:
      | {
          label: string;
          icon: number | Media;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  howItWork?:
    | T
    | {
        title?: T;
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
        id?: T;
      };
  modelComparison?:
    | T
    | {
        title?: T;
        subtitle?: T;
        products?: T;
      };
  certificatesSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        certificates?: T;
      };
  trainingSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        video?:
          | T
          | {
              poster?: T;
              file?: T;
            };
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  reviewsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        reviews?: T;
      };
  faqSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training_select".
 */
export interface TrainingSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  formats?:
    | T
    | {
        title?: T;
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  videoInstructions?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  faq?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  phone?: T;
  email?: T;
  address?: T;
  form?:
    | T
    | {
        title?: T;
        description?: T;
        socialNetworks?:
          | T
          | {
              label?: T;
              icon?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconTextBlock".
 */
export interface IconTextBlock {
  image: number | Media;
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}